### ISSUE TITLE
Not dumping color camera stream

### ISSUE THREAD

**Issue by Justcause23** [sebtoun/DumpKinectSkeleton#4]
Hi guys,

The joints data is dumping into the folder as .csv. But is there any reason why the color camera stream is not dumping into the folder at all? 

Thank you,
JC

**Comment by sebtoun** [comment]
Are you using the -v option ? The default behavior is to only dump skeleton data (I see that it is not very clear from the readme).

**Comment by Justcause23** [comment]
Not sure how to use the -v option. I may have missed something. When I click run, all I get is the following default window:

“Starting capture
Output skeleton data in file output_body.csv
Press X,Q or Control + C to stop capture
Capture rate(s):
1 Skeleton(s) at 30.0 Fps”

JC

**Comment by sebtoun** [comment]
Options like `-v` have to be put after the executable name in the command line (in a `cmd.exe` instance window). If you're not comfortable with command line interfaces or you want to have an icon to launch the application, you can create a shortcut to the executable and in its _Properties_ panel, add options (like `-v`)  after executable path in the _Target_ field (add space between options and path).

**Comment by Justcause23** [comment]
Great. Thank you again.

JC
