### ISSUE TITLE
record and sync video when tracking skeleton using kinect

### ISSUE THREAD

**Issue by h-adams** [sebtoun/DumpKinectSkeleton#5]
Hi, I have been using your code to collect the skeletal data with the Kinect. The data dump appears to be working fine, but I don't get any video? I have Microsoft 4.5 .NET Framework installed, I'm trying to sync the video with the recording of the skeletal data. Thanks Hardeep

**Comment by sebtoun** [comment]
Hi, can you look at the closed issue https://github.com/sebtoun/DumpKinectSkeleton/issues/4 to see if the response helps you ?

**Comment by h-adams** [comment]
Hi, Thanks, but can you give me a little bit more instruction? I’m really new to this.

**Comment by sebtoun** [comment]
Not sure to understand where you need help... 
I asked you to go to this link: https://github.com/sebtoun/DumpKinectSkeleton/issues/4 and read the discussion here to see if that helps. Did you read it ? Where do you need more help ?

It resumes to "use `DumpKinectSkeleton -v -s` to launch the application with synchronized video 
 stream dump enabled"

**Comment by h-adams** [comment]
Ok, I opened command prompt, pointed to the executable on the desktop folder

So I had the following in cmd prompt: C:\Users\admin\Desktop\DumpKinectSkeleton-master\DumpKinectSkeleton.csproj –v –s

**Comment by sebtoun** [comment]
You cannot use source files directly : you have to either build the .exe from sources in Visual Studio or download a prebuilt release here https://github.com/sebtoun/DumpKinectSkeleton/releases.

**Comment by sebtoun** [comment]
Closing this since no recent news from OP, I suppose it worked.

**Comment by h-adams** [comment]
Sorry. Yes it did thanks.
