### ISSUE TITLE
Cannot get Video data, only the skeleton data. 

### ISSUE THREAD

**Issue by sabrinasoraya** [sebtoun/DumpKinectSkeleton#6]
Hi, I tried to run your program but it only outputs the skeleton data to csv, and there is no video data at all. 
And there is no option that I could press 'v'. Do you know what is the problem? Thank you.

**Comment by sebtoun** [comment]
Hi, please see closed issue https://github.com/sebtoun/DumpKinectSkeleton/issues/4 and tell me if you manage to get video stream.

**Comment by sabrinasoraya** [comment]
Hi, thank you I got it :)
